site_name: 'Magknight Documentation'
site_url: 'https://docs.magknight.org/'
repo_name: 'GitHub'
repo_url: 'https://github.com/magknight/aviatorsDocs'
site_description: "Documentation for the Magknight 787: Aviator's Edition for X-Plane 11, now stored in the cloud"
site_author: 'magknight'
copyright: 'magknight'

theme:
  name: 'material'
  language: 'en'
  shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
  custom_dir: 'material'
markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - toc:
        permalink: True
        separator: "_"
    - pymdownx.details
    - meta
nav:
  - Home: "index.md"
  - Frequently Asked Questions: "faq.md"
  - Troubleshooting: "troubleshooting.md"
  #- Tutorials:
  #  - Getting Started: "flightTutorial.md"
  - Reference:
    - Aircraft Settings: "aircraftSettings.md"
  - About: "about.md"
  
# extra:
#   social:
#     - icon: globe
#       link: http://magknight.org
#     - icon: twitter
#       link: https://twitter.com/magknightav
#     - icon: facebook
#       link: https://www.facebook.com/magknightAv

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
